"""
rss_feeds.py — Team RSS feed URLs for injury ingest.
Note: team abbreviations that overlap between NFL/NBA are intentional —
the ingest layer merges them into a single player name → DNP prob lookup.
"""

RSS_FEEDS: dict[str, str] = {
    # ── NFL ───────────────────────────────────────────────────────────────────
    "ARI":  "https://www.azcardinals.com/rss.xml",
    "ATL":  "https://www.atlantafalcons.com/rss.xml",
    "BAL":  "https://www.baltimoreravens.com/rss.xml",
    "BUF":  "https://www.buffalobills.com/rss.xml",
    "CAR":  "https://www.panthers.com/rss.xml",
    "CHI":  "https://www.chicagobears.com/rss.xml",
    "CIN":  "https://www.bengals.com/rss.xml",
    "CLE":  "https://www.clevelandbrowns.com/rss.xml",
    "DAL":  "https://www.dallascowboys.com/rss.xml",
    "DEN":  "https://www.denverbroncos.com/rss.xml",
    "DET":  "https://www.detroitlions.com/rss.xml",
    "GB":   "https://www.packers.com/rss.xml",
    "HOU":  "https://www.houstontexans.com/rss.xml",
    "IND":  "https://www.colts.com/rss.xml",
    "JAX":  "https://www.jaguars.com/rss.xml",
    "KC":   "https://www.chiefs.com/rss.xml",
    "LV":   "https://www.raiders.com/rss.xml",
    "LAC":  "https://www.chargers.com/rss.xml",
    "LAR":  "https://www.therams.com/rss.xml",
    "MIA":  "https://www.miamidolphins.com/rss.xml",
    "MIN":  "https://www.vikings.com/rss.xml",
    "NE":   "https://www.patriots.com/rss.xml",
    "NO":   "https://www.neworleanssaints.com/rss.xml",
    "NYG":  "https://www.giants.com/rss.xml",
    "NYJ":  "https://www.newyorkjets.com/rss.xml",
    "PHI":  "https://www.philadelphiaeagles.com/rss.xml",
    "PIT":  "https://www.steelers.com/rss.xml",
    "SF":   "https://www.49ers.com/rss.xml",
    "SEA":  "https://www.seahawks.com/rss.xml",
    "TB":   "https://www.buccaneers.com/rss.xml",
    "TEN":  "https://www.tennesseetitans.com/rss.xml",
    "WAS":  "https://www.commanders.com/rss.xml",
    # ── NBA ───────────────────────────────────────────────────────────────────
    "ATL_NBA": "https://www.hawks.com/rss.xml",
    "BOS":     "https://www.celtics.com/rss.xml",
    "BKN":     "https://www.nets.com/rss.xml",
    "CHA":     "https://www.hornets.com/rss.xml",
    "CHI_NBA": "https://www.bulls.com/rss.xml",
    "CLE_NBA": "https://www.cavaliers.com/rss.xml",
    "DAL_NBA": "https://www.mavs.com/rss.xml",
    "DEN_NBA": "https://www.nuggets.com/rss.xml",
    "DET_NBA": "https://www.pistons.com/rss.xml",
    "GSW":     "https://www.warriors.com/rss.xml",
    "HOU_NBA": "https://www.rockets.com/rss.xml",
    "IND_NBA": "https://www.pacers.com/rss.xml",
    "LAC_NBA": "https://www.clippers.com/rss.xml",
    "LAL":     "https://www.lakers.com/rss.xml",
    "MEM":     "https://www.grizzlies.com/rss.xml",
    "MIA_NBA": "https://www.heat.com/rss.xml",
    "MIL":     "https://www.bucks.com/rss.xml",
    "MIN_NBA": "https://www.timberwolves.com/rss.xml",
    "NOP":     "https://www.pelicans.com/rss.xml",
    "NYK":     "https://www.knicks.com/rss.xml",
    "OKC":     "https://www.thunder.com/rss.xml",
    "ORL":     "https://www.magic.com/rss.xml",
    "PHI_NBA": "https://www.sixers.com/rss.xml",
    "PHX":     "https://www.suns.com/rss.xml",
    "POR":     "https://www.blazers.com/rss.xml",
    "SAC":     "https://www.kings.com/rss.xml",
    "SAS":     "https://www.spurs.com/rss.xml",
    "TOR":     "https://www.raptors.com/rss.xml",
    "UTA":     "https://www.jazz.com/rss.xml",
    "WAS_NBA": "https://www.wizards.com/rss.xml",
}
